import coding_information_theory_compaction_compression_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace coding_information_theory_compaction_compression_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end coding_information_theory_compaction_compression_foundation_canonical_lane_mathlib
end HautevilleHouse
